# Generated by Django 5.1.6 on 2025-04-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_created_at_alter_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Bangalore', 'Bangalore'), ('Pune', 'Pune'), ('Remote', 'Remote'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('New Delhi', 'New Delhi'), ('Gurugram', 'Gurugram'), ('Noida', 'Noida'), ('Ghaziabad', 'Ghaziabad'), ('Faridabad', 'Faridabad'), ('Kolkata', 'Kolkata'), ('Ahmedabad', 'Ahmedabad'), ('Lucknow', 'Lucknow'), ('Jaipur', 'Jaipur'), ('Chandigarh', 'Chandigarh'), ('Vijayawada', 'Vijayawada'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Bhubaneswar', 'Bhubaneswar'), ('Visakhapatnam', 'Visakhapatnam'), ('Indore', 'Indore'), ('Vadodara', 'Vadodara')], max_length=50),
        ),
    ]
