# Generated by Django 5.1.6 on 2025-03-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker'), ('company', 'Company')], default='job_seeker', max_length=20),
        ),
    ]
