# Generated by Django 5.1.6 on 2025-03-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('profession', models.CharField(choices=[('Python Backend', 'Python Backend'), ('Frontend', 'Frontend'), ('Java Backend', 'Java Backend'), ('Data Science', 'Data Science'), ('PHP', 'PHP')], max_length=100)),
                ('experience_level', models.CharField(choices=[('Fresher', 'Fresher'), ('Intermediate', 'Intermediate'), ('Experienced', 'Experienced')], max_length=50)),
                ('resume_file', models.FileField(upload_to='media/resumes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
            ],
        ),
    ]
