# Generated by Django 5.1.6 on 2025-04-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeats', '0005_alter_payment_base_price_alter_payment_gst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gst',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
